version: '3.8'

services:
  node1:
    image: nicholasliem/block-trade-chain:latest
    container_name: eth-node1
    ports:
      - "8545:8545" # HTTP-RPC API port
      - "30303:30303" # Peer-to-peer communication port
      - "30303:30303/udp" # UDP discovery port
    volumes:
      - ./node1_data:/root/data
    command:
      geth --datadir /root/data --networkid 1234 --http --http.addr 0.0.0.0 --http.port 8545 --http.api personal,eth,net,web3 --nodiscover --allow-insecure-unlock

  node2:
    image: nicholasliem/block-trade-chain:latest
    container_name: eth-node2
    ports:
      - "8546:8545" # HTTP-RPC API port for node 2
      - "30304:30303" # Peer-to-peer communication port for node 2
      - "30304:30303/udp" # UDP discovery port for node 2
    volumes:
      - ./node2_data:/root/data
    command:
      geth --datadir /root/data --networkid 1234 --http --http.addr 0.0.0.0 --http.port 8545 --http.api personal,eth,net,web3 --nodiscover --allow-insecure-unlock